### ISSUE TITLE
Question: эта библиотека нормально работает с KKMserver 2.1.40.42 от 13.01.2021?

### ISSUE THREAD

**Issue by Janealter** [Muraveiko/kkmserver#12]
Библиотека последний раз обновлялась 4 года назад, а новые версии KKMServer выходят регулярно. Есть ли какие-то проблемы с поддержкой новых версий?

**Comment by Muraveiko** [comment]
Есть проблемы. На момент написания поддерживался 1.0. 
За 4 года как вы заметили было много изменений.
Так что для актуальных версий сгодится только в качестве основы для доработки.
